user:
  outputs:
    default:
      account: HFNAIME-AM30253
      auth_type: password
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: DBT_TUTORIAL_DEV
      password: Aishwarya78@snowflake
      retry_on_database_errors: true
      role: ACCOUNTADMIN
      schema: dbt_aishwarya781998
      threads: 6
      type: snowflake
      user: Aishwarya78
      warehouse: COMPUTE_WH
  target: default
